#Base64 your secreats
#echo -n "hello world" | base64

apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: production
type: Opaque
data:
  API_KEY: aGVsbG8gd29ybGQ=

--- 
apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: staging
type: Opaque
data:
  API_KEY: aGVsbG8gd29ybGQ=

--- 
apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: qa
type: Opaque
data:
  API_KEY: aGVsbG8gd29ybGQ=

--- 
apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: dev
type: Opaque
data:
  API_KEY: aGVsbG8gd29ybGQ=