apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace : production
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace : staging
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi


---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace : qa
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace : dev
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi