---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: demoapp
  namespace: production
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: demoapp
  chart:
    git: git@github.com:evalsocket/k8s-setup
    path: demoapp/helm/
    ref: master
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: evalsocket/demoapp:staging
      tag: latest
      config: []
      secret: []
      pullPolicy: IfNotPresent 
      resources:
        requests:
          cpu: 200m
          memory: 300Mi
      # Example (replace readinessProbe: {} with the following):
      readinessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 3
        periodSeconds: 5
      # Example (replace livenessProbe: {} with the following)::
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 40
        periodSeconds: 10  
    service:
      name: Node
      type: NodePort
      servicePort: 3000
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      metrics:
        cpu:
          targetAverageUtilization: 70
        memory:
          targetAverageUtilization: 70
    services:
    base:
      enabled: false
      replicaCount: 1
      image:
        tag : v0.9.9
      weight: 100
    istio:
      enabled: false
      weight: 100