apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
  namespace: production
data:
  NODE_ENV: production 
  PORT: "8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
  namespace: staging
data:
  NODE_ENV: production 
  PORT: "8080"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
  namespace: qa
data:
  NODE_ENV: production 
  PORT: "8080"

---

apiVersion: v1
kind: ConfigMap
namespace: dev
metadata:
  name: common-configmap
  namespace: dev
data:
  NODE_ENV: production 
  PORT: "8080"