kind: Service
apiVersion: v1
metadata:
 name: demo
 namespace : production
Spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 8080

--- 
kind: Service
apiVersion: v1
metadata:
 name: demo
 namespace : staging
Spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 8080

--- 
kind: Service
apiVersion: v1
metadata:
 name: demo
 namespace : qa
Spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 8080

--- 
kind: Service
apiVersion: v1
metadata:
 name: demo
 namespace : dev
Spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 8080